### get houses
GET http://localhost:6969/houses

### get the house by id
GET http://localhost:6969/houses/6566d4fc924d9aad45c8031c

### borrar una casa
DELETE http://localhost:6969/houses/6566d4fc924d9aad45c8031c
### actualizar una casa
PATCH http://localhost:6969/houses/6566d4fc924d9aad45c8031c
Content-Type: application/json

{
  "name": "Casa Epica",
  "price": 8500,
  "description": "Excelente casa para dormir de noche",
  "location": "Minas",
  "details": "Se cae a pedazos a veces",
  "locationURL": "https://www.example.com/location?lat=37.7749&lon=-122.4194",
  "bathroom": 1,
  "kitchen": 1 ,
  "bedroom": 2,
  "garage": true,
  "garden": true
}

